### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=WebStorm

###

GET request to example server
GET http://localhost:3000/animals

###

GET http://localhost:3000/animals/id/4

###
GET http://localhost:3000/animals/endangered

###
GET http://localhost:3000/animals/habitat/Savanna

###
GET http://localhost:3000/animals/species?species=Ryba

###
POST http://localhost:3000/animals/addanimal
Content-Type: application/json; charset=utf-8

{
  "name": "Łkoy",
  "species": "wiktor",
  "age": 13,
  "isEndangered": true,
  "habitat": "Forest"
}

###

PUT http://localhost:3000/animals/updateanimal/3
Content-Type: application/json

{
    "id": 4,
    "name": "kotek",
    "species": "wiktor",
    "age": 10,
    "isEndangered": true,
    "habitat": "Ocean"
  }

###
DELETE http://localhost:3000/animals/deleteanimal/4